### ISSUE TITLE
How to use is broken

### ISSUE THREAD

**Issue by vorburger** [vorburger/opendaylight-simple#73]
https://github.com/vorburger/opendaylight-simple#how-to-use is broken since the OFP integration:

```
2018-12-19T13:02:43,389 | ERROR | main             | Main                             | Failed to start up, going to close up and exit
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: org/osgi/service/blueprint/container/ComponentDefinitionException
  at org.opendaylight.openflowplugin.simple.OpenFlowJavaWiring.<init>(OpenFlowJavaWiring.java:33)
  at org.opendaylight.openflowplugin.simple.OpenFlowJavaWiring.class(OpenFlowJavaWiring.java:33)
  while locating org.opendaylight.openflowplugin.simple.OpenFlowJavaWiring
    for the 1st parameter of org.opendaylight.openflowplugin.simple.OpenFlowPluginWiring.getOpenFlowJavaWiring(OpenFlowPluginWiring.java:55)
  at org.opendaylight.openflowplugin.simple.OpenFlowPluginWiring.getOpenFlowJavaWiring(OpenFlowPluginWiring.java:55) (via modules: org.opendaylight.genius.simple.GeniusWiring -> org.opendaylight.openflowplugin.simple.OpenFlowPluginWiring)
  while locating org.opendaylight.openflowjava.protocol.spi.connection.SwitchConnectionProviderList
    for the 2nd parameter of org.opendaylight.openflowplugin.impl.OpenFlowPluginProviderImpl.<init>(OpenFlowPluginProviderImpl.java:142)
  at org.opendaylight.openflowplugin.impl.OpenFlowPluginProviderImpl.class(OpenFlowPluginProviderImpl.java:89)
  while locating org.opendaylight.openflowplugin.impl.OpenFlowPluginProviderImpl
  while locating org.opendaylight.controller.md.sal.binding.api.BindingService
Caused by: java.lang.NoClassDefFoundError: org/osgi/service/blueprint/container/ComponentDefinitionException
	at org.opendaylight.controller.simple.ConfigReader.read(ConfigReader.java:85)
	at org.opendaylight.openflowplugin.simple.OpenFlowJavaWiring.<init>(OpenFlowJavaWiring.java:35)
	at org.opendaylight.openflowplugin.simple.OpenFlowJavaWiring$$FastClassByGuice$$105eeb5.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:402)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at org.opendaylight.infrautils.simple.Main.<init>(Main.java:37)
	at org.opendaylight.infrautils.simple.ShellMain.<init>(ShellMain.java:34)
	at org.opendaylight.genius.simple.GeniusMain.main(GeniusMain.java:19)
Caused by: java.lang.ClassNotFoundException: org.osgi.service.blueprint.container.ComponentDefinitionException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
```

**Comment by vorburger** [comment]
also (very minor) cb49bbc4a164a1e88387eb21e605f2e2ab63d211

**Comment by vorburger** [comment]
`org.osgi.compendium` is `provided`, and I guess this makes `maven-jar-plugin` not include it.

We later should not have any dependency on `org.osgi.compendium` at all, but we can just add it, for now...
